name: Build and Release
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
jobs:
  check-bats-version:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: cd vcpkg && bootstrap-vcpkg.bat

      - uses: ilammy/msvc-dev-cmd@v1

      - run: cmake --preset default

      - run: cmake --build --preset default --config Release

      - name: Package
        run: |
          mkdir dist
          7z a dist/MuteApp.zip builds/Release/MuteApp.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/*
